import Head from "next/head";
import Header from '../Header'
import Hero from '../Hero'
import TextInfinite from "../TextInfinite";

export default function CreateUserPage() {

  return (
    <>
      <Head>
        <title>Criar Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header typeButton={'Início'}/>
      <Hero />
      <TextInfinite />
      
    </>
  )
}
