import Head from 'next/head'
import Header from '../Header'
import Hero from '../Hero'
import TextInfinite from '../TextInfinite'
import FormCreate from '../FormCreate'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.min.css'

export default function CreateUserPage() {
  return (
    <>
      <Head>
        <title>Criar Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header typeButton={'Início'} />
      <Hero />
      <TextInfinite />
      <FormCreate />
      <ToastContainer
        position="top-right"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover={false}
      />
    </>
  )
}
