import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Início - Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Os <span>Melhores</span> Usuários</h1>
      <h2>Texto 2</h2>
      <h3>Texto 3</h3>
      <p>Lorem ipsum dolor sit amet, consectet</p>
    </div>
  )
}
