import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from 'react-redux';
import Header from '../Header'
import Hero from '../Hero'
import TextInfinite from "../TextInfinite";
import Users from "../Users";
import { RootState } from "../../store";
import { asyncGetUsers } from '../../store/Users.store';

export default function HomePage() {
  const dispatch = useDispatch()
  const {users} = useSelector((state: RootState) => state.users)
  const [isSearch, setIsSearch] = useState(false)
  const [userFilter, setUserFilter] = useState([])

  useEffect(() => {
    const getUsers = () => dispatch(asyncGetUsers())
    getUsers()
  }, [])

  console.log(isSearch)

  return (
    <>
      <Head>
        <title>Início - Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setIsSearch={setIsSearch} setUserFilter={setUserFilter}/>
      <Hero />
      <TextInfinite />
      <Users users={isSearch ? userFilter : users}/>
    </>
  )
}
